### PR TITLE
add detection for doctests

### PR DESCRIPTION
**Pull request by Freax13**
- detect doctests as tests

### CODE REVIEW

**Comment by phil-opp** [comment]
Thanks for the PR! Could you clarify how you're using doc tests with bootimage? As far as I know, doc tests don't work in combination with custom test frameworks.

**Comment by Freax13** [comment]
first of all I should note that this isn't working rn because of a bug in cargo (https://github.com/rust-lang/cargo/pull/8094) 

i'm using something similar to `cargo xtest --target bare_x86_64.json -Z doctest-xcompile` to run the doctests

doctests don't work with custom test frameworks. rustdoc basically just individually wraps the code for each test in a main method (unless you provide your own) and compiles it.

example from my code:
```rust
/// acquire the lock
/// ```
/// # #![cfg_attr(target_os = "none", no_std, no_main)]
/// # lemon_std::entry_point!(test);
/// # async fn test() {
/// # use lemon_std::sync::SpinMutex;
/// let lock = SpinMutex::new("Foo");
/// lock.lock();
/// # lemon_std::arch::exit(true);
/// # }
/// # main();
/// ```
pub fn lock(&self) -> SpinMutexGuard<'_, D> {
```

**Comment by phil-opp** [comment]
Thanks for the clarification! I wasn't aware of the `-Z doctest-xcompile`, but it's great to see that docstests are coming to no_std applications.

> doctests don't work with custom test frameworks. rustdoc basically just individually wraps the code for each test in a main method (unless you provide your own) and compiles it.

So they're basically integration tests with disabled test harness (as described in https://os.phil-opp.com/testing/#no-harness-tests)?



> first of all I should note that this isn't working rn because of a bug in cargo ([rust-lang/cargo#8094](https://github.com/rust-lang/cargo/pull/8094))

I think it might make sense to delay merging this PR until this cargo bug is resolved and we can actually try whether this PR works. It might be also a good idea to add an automated test for this then to check the behavior on CI and ensure that we don't break it on future changes. Would that be okay with you?

**Comment by Freax13** [comment]
> So they're basically integration tests with disabled test harness (as described in https://os.phil-opp.com/testing/#no-harness-tests)?

pretty much, yeah

> I think it might make sense to delay merging this PR until this cargo bug is resolved and we can actually try whether this PR works.

rust 1.43 just got released, so the latest cargo on nightly finally contains the fix. do you want me to write an example for doctests (probably something similar to test-basic-boot)?

**Comment by Freax13** [comment]
?

**Comment by phil-opp** [comment]
Sorry for the delay! Yes, I think some example that is tested on CI would be great.

**Comment by phil-opp** [comment]
There are a few warnings for the new doctest test, otherwise this looks very good.

**Comment by Freax13** [comment]
that should have got rid of the warning

**Comment by phil-opp** [comment]
Published as v0.7.10

**Pull request merged**
