### PR TITLE
Pad boot image to block size

### LINKED ISSUE #35: Support VirtualBox: Ensure that binary size is a multiple of 512 bytes
For some reason VirtualBox expects that disk images are a multiple of 512 bytes. We had an option to add the required padding in an old version of `bootimage` but we haven't ported that option to the new build system yet.

Reported in  https://github.com/phil-opp/blog_os/issues/403#issuecomment-480662955

### PR DESCRIPTION
**Pull request by toothbrush7777777**
Closes #35.

### CODE REVIEW

**Comment by phil-opp** [comment]
Thanks a lot! Looks good to me overall.

One small nit: Could you rename the first `padding` binding to something else, e.g. `remainder`? Then we wouldn't have two bindings with the same name but different semantics.

**Comment by toothbrush7777777** [comment]
@phil-opp Done. I also formatted the changes as suggested by `cargo fmt -- --check`..

**Comment by phil-opp** [comment]
Thanks!

bors r+

**Comment by toothbrush7777777** [comment]
@phil-opp Whoops, looks like I shouldn't have done the other formatting then.

**Comment by phil-opp** [comment]
bors r-

I think we can merge this manually.

**Comment by phil-opp** [comment]
Seems like the test [failed on Windows](https://dev.azure.com/rust-osdev/bootimage/_build/results?buildId=270):

> Error: I/O error: failed to pad boot image to a multiple of the block size: Access is denied. (os error 5)

**Comment by toothbrush7777777** [comment]
@phil-opp Any idea what the problem could be?

**Comment by toothbrush7777777** [comment]
I found a comment which seems related:

> `.append(true)` doesn't set all the bits of `GENERIC_WRITE`, it misses the `FILE_WRITE_DATA` bit as @retep998 mentioned. […]
> 
> — https://github.com/rust-lang/rust/issues/54118#issuecomment-420299904

I guess that whatever API that Rust uses in `set_len` on Windows requires that flag. I've changed the code to use `write(true)` instead of `append(true)` and all the checks have now successfully passed.

**Comment by phil-opp** [comment]
Thanks for investigating! Let's get this merged!

**Comment by phil-opp** [comment]
Thanks a lot for tackling this! I will publish a new version tomorrow when I'm at my computer again.

**Comment by toothbrush7777777** [comment]
@phil-opp Cool, that will be great.

**Comment by phil-opp** [comment]
Released as version 0.7.4.

**Pull request merged**
