### PR TITLE
Rewrite bootimage to make bootloader a "normal" dependency

### PR DESCRIPTION
**Pull request by phil-opp**
This changes the way the bootloader dependency is specified in a breaking way. The new version is **already released as `0.5.0-beta`**. Please report any problems you find and let me know what you think!

## Migration guide

The plan is to link this guide from the error messages.

### How it worked in version 0.4

In 0.4, the bootloader dependency was defined in the following way:

```toml
# in your Cargo.toml

[package.metadata.bootimage.bootloader]
name = "bootloader"                 # The bootloader crate name
precompiled = false                 # Whether the bootloader crate is precompiled
version = ""                        # The bootloader version that should be used
git = ""                            # Use the bootloader from this git repository
branch = ""                         # The git branch to use (defaults to master)
path = ""                           # Use the bootloader from this local path
target = "x86_64-bootloader.json"   # Target triple for compiling the bootloader
```

When the `package.metadata.bootimage.bootloader` table was missing completely, it defaulted to:

```toml
[package.metadata.bootimage.bootloader]
name = "bootloader_precompiled"
precompiled = true
```

### The New Way in 0.5

Instead of specifying the bootloader dependency in a `package.metadata` section and letting `bootimage` interpret it, we just specify the bootloader as a normal cargo dependency:

```toml
# in your Cargo.toml

[dependencies]
bootloader = "0.2.0-alpha"
```

The bootloader configuration table has shrunk to:

```toml
[package.metadata.bootimage.bootloader]
name = "bootloader"                 # The crate name of the bootloader dependency
target = "x86_64-bootloader.json"   # Target triple for compiling the bootloader
```

## TODO

- [x] Adjust the help and error messages
- [x] Add support for precompiled bootloaders (e.g. via a cargo feature on the bootloader)
    - ~~Alternatively: Make the bootloader build with LLD~~ (maybe sometime in the future)
- [x] Add a `lib.rs` to the bootloader, that re-exports the `BootInformation` type of the `os_bootinfo` crate (done in https://github.com/rust-osdev/bootloader/pull/20)
    - This way we solve the version mismatch problem (that the kernel uses a different bootinfo version than the bootloader).

### CODE REVIEW

**Comment by phil-opp** [comment]
To test the new `bootimage` in combination with the new `bootloader`:

```
> cargo install bootimage --version "^0.5.0-beta" --force
```

In your `Cargo.toml` add either:

```toml
[dependencies]
bootloader = "0.2.0-beta"    # only works on linux
```

or the precompiled variant:

```toml
[dependencies]
bootloader_precompiled = "0.2.0-beta"
```

Replace your `_start` function with the following:

```rust
#[macro_use]
extern crate bootloader;

#[cfg(not(test))]
entry_point!(kernel_main);

fn kernel_main(boot_info: &'static bootloader::bootinfo::BootInfo) -> ! {…}
```

Try `bootimage run`, `bootimage test`, `cargo test`, etc. and report your findings.

**Comment by phil-opp** [comment]
Published as version 0.5

**Comment by yjhmelody** [comment]
@phil-opp 
bootimage run, bootimage test, cargo test. 
Everything is OK. But I don't know what has been changed.

```toml
[dependencies]
volatile = "0.2"
spin = "0.4"
uart_16550 = "0.1.0"
x86_64 = "0.2"
bootloader = "0.2" # only works on linux
bootloader_precompiled = "0.2"
```

**Comment by phil-opp** [comment]
@yjhmelody The problem is that the bootloader does not link with the `LLD` linker, because it doesn't support some relocation that is generated for the 16 bit code. So we're currently use the linux system linker for linking, which means that it does not work on Windows and macOS.

This is the reason that we have the `bootloader_precompiled`. Like the name says, it's already compiled so it should work on all OSes. When you're using this version, you don't need the `bootloader` dependency. So try to remove it:

```toml
[dependencies]
volatile = "0.2"
spin = "0.4"
uart_16550 = "0.1.0"
x86_64 = "0.2"
bootloader_precompiled = "0.2"
```

**Pull request merged**
